baseURL: 'https://matthew.nz/'
languageCode: en-nz
title: Matthew's Blag
theme: basalt

uglyurls: true

menu:
  main:
    - name: About Me
      url: /
      weight: 1

    - name: Posts
      url: /posts.html
      weight: 2

# Don't use inline styles for code
markup:
  highlight:
    noClasses: false
