baseURL: 'https://matthew.nz/'
languageCode: en-nz
title: Matthew's blag
theme: rose-pine

uglyurls: true

menu:
  main:
    - name: About Me
      url: /
      weight: 1

    - name: Posts
      url: /posts.html
      weight: 2

    - name: Reading
      url: /reading.html
      weight: 3

# Don't use inline styles for code
markup:
  highlight:
    noClasses: false
