baseURL: 'https://matthew.nz/'
languageCode: en-nz
title: Matthew's Blag
theme: basalt

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts/
      weight: 2
