baseURL: 'https://matthew.nz/'
languageCode: en-nz
title: Matthew's Blag
theme: basalt

permalinks:
  posts: '/:year/:month/:title/'

menu:
  main:
    - name: About Me
      url: /
      weight: 1

    - name: Posts
      url: /posts/
      weight: 2

# Don't use inline styles for code
markup:
  highlight:
    noClasses: false
